name: Build Tagged Release Version

on:
  push:
    tags:
    - '**'
permissions:
  contents: read

jobs:
  natives:
    uses: PC-Logix/OC-JNLua/.github/workflows/build-natives.yml@03cbd4b9e73135591a0a9af348381d8783ec927c
    with:
      native_version: ${{ github.ref_name }}

  build:
    needs: natives
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Download reproducibly built OC-JNLua natives
        uses: actions/download-artifact@v4
        with:
          name: OC-JNLua-Natives
          path: build/native-dependencies
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build -Prelease_tag="${{ github.ref_name }}" -PjnluaNativesDirectory=build/native-dependencies
      - name: Publish Maven artifacts
        run: ./gradlew publish -Prelease_tag="${{ github.ref_name }}" -PjnluaNativesDirectory=build/native-dependencies
        env:
          ORG_GRADLE_PROJECT_maven_user: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_maven_password: ${{ secrets.MAVEN_PASSWORD }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenComputers
          path: build/libs/*.jar
